name: dashboard
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.11
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configuration
flutter:
  uses-material-design: true

  assets:
    - images/img.png
    - images/img_1.png
    - images/img_2.png
    - images/img_3.png
    - images/img_4.png
    - images/img_5.png

